mindverse/Second-Me

lpm_kernel/L2/data_pipeline/graphrag_indexing/settings.yaml

Due to validation by graphrag, many models fail to pass; thus, a default encoding model has been added. Although this may result in an imprecise token count, the resulting error is acceptable.

fix: add default embedding model to support none openai model

---

lpm_kernel/file_data/trainprocess_service.py

The training process skips the model download step when the model directory exists but is missing required files (like `config.json`), causing training to fail later.
- Added check for `config.json` file in addition to model directory
- Automatically downloads model if directory or config is missing
- Fixed error handling to use correct ProcessStep enum
Verified on Apple M4 Pro with 24GB RAM that:
- Empty model directories trigger download
- Directories missing config.json trigger download
- UI correctly shows download progress
This resolves the issue where users manually place model files in the correct directory but training fails due to missing configuration files.

Fix model download step being skipped during training

---

.gitignore
lpm_kernel/L0/l0_generator.py
lpm_kernel/L1/shade_generator.py
lpm_kernel/L1/topics_generator.py
lpm_kernel/L2/data.py
lpm_kernel/L2/data_pipeline/data_prep/diversity/diversity_data_generator.py
lpm_kernel/L2/train.py
lpm_kernel/L2/utils.py
lpm_kernel/api/common/script_runner.py
lpm_kernel/api/domains/trainprocess/routes.py
lpm_kernel/common/llm.py
lpm_kernel/common/logging.py
lpm_kernel/configs/logging.py
lpm_kernel/file_data/chunker.py
lpm_kernel/file_data/document_service.py
lpm_kernel/file_data/embedding_service.py
lpm_kernel/file_data/trainprocess_service.py
lpm_kernel/kernel/l1/l1_manager.py
lpm_kernel/utils.py

The logging configuration is centrally defined in `lpm_kernel/configs/logging.py`, which creates a dedicated logger named `train_process` for training procedures and implements a `rename_existing_log_file()` function. During application startup, this function automatically renames old training logs with timestamp suffixes.
The logging system initialization is implemented in `lpm_kernel/common/logging.py`. 
Training-related scripts like `TrainProcessService` use the `train_process` logger, consolidating all logs into `train/train.log`. Monitoring functions `_monitor_model_download` and `_monitor_training_progress` directly read from this training log file.
The `/logs` API endpoint has been modified to stream logs from `train.log`. Various components now output to this unified log:
- Model …

feat(logging): separate training log

---

lpm_kernel/api/file_server/handler.py

When I uploaded the file yesterday and restarted the project today, I encountered this error.
A syntax error occurs when running `make start` command due to backslashes in f-string expressions, resulting in application startup failure. The error message shows:
```
Traceback (most recent call last):
... ...
File "/Users/.../Second-Me/lpm_kernel/api/file_server/handler.py", line 67
if item.is_file()
^^
SyntaxError: f-string expression part cannot include a backslash
```
- Fix f-string syntax error caused by backslashes
- Use Path().as_posix() for consistent path formatting
1. The original code used a combination of `os.path.join()` and `replace()` for path handling:
```python
path=os.path.join(path, item.name).replace("\\", "/"),
url=f"/raw_content/{os.path.join(path, …
```

fix: Replace file path handling with pathlib to resolve f-string syntax error

---

lpm_kernel/L2/download_model.sh

otherwise the program will raise an error:
```
$ sh -x lpm_kernel/L2/download_model.sh
+ python lpm_kernel/L2/utils.py Qwen/Qwen2.5-0.5B-Instruct
2025-03-26 16:55:56,135 - download_logger - INFO - Starting download of model: Qwen/Qwen2.5-0.5B-Instruct
2025-03-26 16:55:56,135 - download_logger - INFO - Will be saved to: /Users/xyb/projects/second-me/resources/L2/base_models/Qwen/Qwen2.5-0.5B-Instruct
2025-03-26 16:55:56,135 - download_logger - ERROR - Error downloading model: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'Qwen/Qwen/Qwen2.5-0.5B-Instruct'. Use `repo_type` argument if needed.
Traceback (most recent call last):
File "/Users/xyb/projects/second-me/lpm_kernel/L2/utils.py", line 555, in <module>
save_hf_model(sys.argv[1])
File …
```

fix: download qwen model to the correct directory

---

lpm_frontend/src/components/roleplay/RoleCard.tsx
lpm_frontend/src/components/roleplay/ShareRoleModal.tsx
lpm_frontend/src/components/spaces/ShareSpaceModal.tsx
lpm_frontend/src/components/upload/RegisterUploadModal.tsx
lpm_frontend/src/utils/copy.ts

This PR introduces a new clipboard copy method that gracefully handles cases where navigator.clipboard is unavailable or not supported.
Changes include:
- Adding a new function `copyToClipboard` that attempts to use the modern clipboard API when available in a secure context.
- Falling back to a manual copy approach using a temporary textarea (`manualCopyFallback`) if the clipboard API fails or is unsupported.
This enhancement prevents errors when copying to the clipboard in unsupported environments and improves overall robustness.

fix: copy to clipboard

---

scripts/conda_utils.sh

When installing Anaconda on an M1 Mac using `brew install --cask anaconda`, encounter an error stating that conda.sh cannot be found when running `make start`. 
This PR adds the default Homebrew installation path for conda.sh on Apple Silicon (M1) Macs to the detection list.

fix: add m1 homebrew conda.sh path

---

lpm_kernel/configs/config.py

When a string-type `env_file` parameter is passed into the `from_env` method, it causes an error because strings do not have an `exists()` method.
Convert the incoming `env_file` parameter to a `Path` object, regardless of whether it is a string or already a Path object.
The following scenarios have been tested:
Not passing the env_file parameter
Passing a string-type env_file
Passing a Path object-type env_file

Fix: Ensure env_file is a Path

---

README.md

This PR adds a new **manual setup guide** section under the documentation to help contributors and users deploy the Second-Me project in various environments without relying solely on the automated `setup.sh` and `start_local.sh` script.
The guide covers:
- Conda + Poetry based Python environment setup
- Manual frontend installation
- Manual `llama.cpp` build instructions
- Local SQL and ChromaDB initialization
- Backend and frontend startup commands
- Cross-server deployment tips
📁 Scripts referenced:
- [`scripts/setup.sh`](https://github.com/mindverse/Second-Me/blob/master/scripts/setup.sh)
- [`scripts/start_local.sh`](https://github.com/mindverse/Second-Me/blob/master/scripts/start_local.sh)
Some users may prefer or require a manual setup process due to platform differences, network …

【Multi-Platform】Docs: Add cross-platform manual setup guide for backend and frontend

---

lpm_kernel/L2/data.py

The original code only processed embedding model names starting with "openai/", leaving other model names unhandled. This change adds an else branch to ensure non-OpenAI embedding model names are also correctly set in the configuration. This PR specifically addresses the issue where encounter non-OpenAI embedding model handling during graphrag_indexing would cause the program to hang.
Changes:
- Added an else clause to the if embedding_name.startswith("openai") condition
- For non-OpenAI embedding model names, the raw name is now directly assigned
- Fixed the program hanging issue during graphrag_indexing when  embedding model is not properly set

fix: support for non-OpenAI embedding model in graphrag_indexing()

---

lpm_kernel/file_data/trainprocess_service.py

On Windows, path separator is "\\" instead of "/" on Linux/macOS.
Before the fix, `os.path.join(os.getcwd(), "data/progress")` just adds a line separator, and left "data/progress" untouched.
But after `os.path.normpath`, the "/" gets transformed into "\\" on Windows, therefore failing the check:
https://github.com/mindverse/Second-Me/blob/ff61385ac606d7384c6e5c3c5ab7cba70acf8435/lpm_kernel/file_data/trainprocess_service.py#L85
This PR fixes the problem by feeding "data" and "progress" separately, then Python will treat them using platform-specific separators.
Tested locally and it works on Windows 11, Python 3.12.4.

fix: Invalid progress file path on Windows

---

docs/Custom Model Config(Ollama).md

When deploying Ollama as a local service, it is recommended to use `127.0.0.1` as the IP address rather than `localhost`. This is because in environments with an active VPN, DNS resolution for `localhost` may not resolve to `127.0.0.1`, leading to connection issues.
This distinction behaves differently across client libraries:
- **requests library**: When using the requests library to connect to Ollama local services, `127.0.0.1` and `localhost` are typically equivalent since these requests are generally not routed through VPN to external networks, allowing DNS to correctly resolve `localhost` to `127.0.0.1`.
- **OpenAI SDK**: When using the OpenAI SDK, VPN may route traffic to external networks, causing `localhost` to resolve to an address other than `127.0.0.1`, preventing proper …

fix: use 127.0.0.1 instead of localhost for Ollama connections

---

lpm_kernel/utils.py

**Problem**
When configuring custom models, `tiktoken` may fail to retrieve `tokenizers` for non-OpenAI models. Specifically, `tokenizers` for models like `Qwen2.5` and `Claude` are not available in the `tiktoken` library, resulting in the following error:
```
KeyError: 'Could not automatically map qwen2.5:1.5b to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
```
**Solution**
This PR adds compatibility handling by using the `cl100k_base` tokenizer as a default fallback for models not supported by `tiktoken`. This approach ensures that operations requiring tokenization can proceed without errors for non-OpenAI models like Qwen2.5 and Claude.

Fix tiktoken compatibility with non-OpenAI models

---

lpm_kernel/L1/l1_generator.py
lpm_kernel/L1/shade_generator.py
lpm_kernel/L1/status_bio_generator.py
lpm_kernel/L1/topics_generator.py

- Add _top_p_adjusted flag to track parameter adjustments
- Implement _fix_top_p_param to adjust invalid top_p values
- Enhance _call_llm_with_retry with parameter adjustment retry mechanism
- Apply consistent implementation across all generator classes
- Improve error logging for API error debugging
---
When I request LLM API with `top_p=0`, some model providers （such as DeepSeek）reject the request with a 400 error, indicating that the valid range for `top_p` is (0, 1.0]. This causes API calls to fail in various generators(L1), including `L1Generator`, `TopicsGenerator`, `ShadeGenerator`, and `StatusBioGenerator`.
1. The original code had these issues:
```python
self.model_params = {
"temperature": 0,
"top_p": 0,  # This value is rejected by some LLM providers
}
```
2. The problems with …

fix: implement dynamic top_p parameter adjustment for LLM API calls

---

lpm_kernel/L2/data_pipeline/graphrag_indexing/settings.yaml

Added encoding_model to default_embedding_model in settings.yaml
**Changes:**
- Added encoding_model configuration to the default_embedding_model section in settings.yaml
- This change prevents encoding errors during the GraphRAG process by explicitly specifying the encoding model to be used

fix: hotfix for missing encoding_model_name in setting.yaml(GraphRAG)

---

lpm_kernel/api/domains/trainprocess/routes.py
pyproject.toml

Fixes #170 by determining the encoding prior to read.
Tested successfully on Windows 11, and further testing on other environments might be necessary.
Note: This PR **adds a new dependency**, I am not sure if this is acceptable, as it may need people to rerun **poetry install** on upgrade.

fix: Wrong encoding on reading backend.log

---

scripts/restart-force.sh

i noticed an issue with the paths to the `stop.sh` and `start.sh` scripts. they were relative paths, which could break if the script is run from a different directory.
i've updated the paths to use the `${SCRIPT_DIR}` variable, which ensures the correct absolute path is used, regardless of the current working directory.
this should prevent any errors related to incorrect paths when invoking the scripts.

fix: incorrect script paths in `stop.sh` and `start.sh`

---

docker/app/init_chroma.py

I noticed that both `documents_collection` and `chunks_collection` were referencing the same object, which caused unexpected behavior during processing. I’ve separated them so they now operate independently.

fix: collection reference bug in document chunking logic

---

lpm_kernel/api/domains/kernel2/routes_l2.py

Fix #183 by checking if directory exists.
Tested on Windows 11.

fix: Find correct llama-server location

---

lpm_kernel/api/domains/loads/load_service.py

When multiple Load records exist in the system, the get_current_load method returns an error message "Multiple load records exist in the system, please clean up first" with a 400 status code, causing the API call to fail. This situation may occur when users create multiple Load records, affecting normal system usage.
- Create one Load record in the system
- Create another Load record without deleting the existing one
- Call the /api/loads/current API endpoint
- Observe that the API returns a 400 error with the message "Multiple load records exist in the system, please clean up first"
- The system requires users to manually clean up the database, which is difficult for regular users
- API call failures prevent dependent features from working properly
- Negative impact on user experience …

fix: fix multi-upload

---

README.md
lpm_kernel/api/domains/loads/load_service.py
lpm_kernel/api/domains/trainprocess/routes.py
lpm_kernel/train/trainprocess_service.py

1. **Parameter Validation Enhanced**: Modified the TrainProcessService initialization function to require the `current_model_name` parameter, ensuring it cannot be None, thus guaranteeing a valid model name at all times
2. **Singleton Access Interface**: Added the `get_instance()` class method, providing a unified interface for obtaining the singleton instance, conforming to standard singleton pattern design
1. **Invocation Method Update**: Updated direct TrainProcessService instance construction calls to use the get_instance() method
2. **Code Format Optimization**: Simplified some instance creation code formats for improved readability
3. **Redundant Endpoint Removal**: Removed the no-longer-needed "/model_name" GET route
1. **Code Consistency**: Ensured access consistency through a …

Optimize TrainProcessService Singleton Pattern Implementation

---

lpm_kernel/api/domains/trainprocess/routes.py
lpm_kernel/api/domains/trainprocess/training_params_manager.py

Currently, the retrain method lacks the ability to update training parameters in the same way as the start_process method. This enhancement adds parameter handling capabilities to the retrain method and modifies the `TrainingParamsManager.update_training_params` method to support resetting parameters when retraining.
- Enhanced the retrain endpoint to accept the same training parameters as start_process:
- learning_rate
- number_of_epochs
- concurrency_threads
- data_synthesis_mode
- use_cuda
- is_cot
- Modified the `TrainingParamsManager.update_training_params` method to accept a `use_previous_params` flag
- Set `use_previous_params=False` in the retrain method to ensure parameters are reset when retraining
- Updated endpoint documentation to reflect new parameters
- Added proper …

preserve training param

---

README.md
lpm_frontend/src/app/dashboard/playground/chat/page.tsx
lpm_frontend/src/components/OnboardingTutorial/index.tsx
lpm_frontend/src/components/ThinkingModelModal/index.tsx
lpm_frontend/src/components/train/TrainingConfiguration.tsx
lpm_frontend/src/layouts/DashboardLayout/Menu/index.tsx
lpm_kernel/api/domains/trainprocess/training_params_manager.py

This PR includes multiple UI improvements and optimizations for the Thinking Model configuration, enhancing user experience and addressing potential issues with default values.
- Improved handling of Thinking Model configuration when backend returns null or undefined values
- Set default model name to "deepseek-reasoner" and default API endpoint to "https://api.deepseek.com"
- Ensured input fields show appropriate values regardless of backend response
- Translated Chinese comments to English for better code internationalization
- Enhanced error message wording from "Cancel the current train" to "Cancel the current training run"
- Reorganized the Thinking Model tooltip position for better readability
- Added detailed explanation for Chain of Thought (CoT) functionality to help users …

UI Improvements and Thinking Model Configuration Enhancements

---

scripts/setup.sh

graphrag is re-installed every time due to that setup.sh fails to find installed graphrag target version when two "Versions:" is found in the environment:
```
Version: 1.2.1.dev27
Metadata-Version: 2.3
```
when the output of `poetry run pip show graphrag 2>/dev/nul` is
```
Name: graphrag
Version: 1.2.1.dev27
Summary: GraphRAG: A graph-based retrieval-augmented generation (RAG) system.
Home-page:
Author: Alonso Guevara Fernández
Author-email: alonsog@microsoft.com
License: MIT
Location: /workspace/myapp/.venv/lib/python3.12/site-packages
Requires: aiofiles, azure-cosmos, azure-identity, azure-search-documents, azure-storage-blob, devtools, en-core-web-md, environs, fnllm, future, graspologic, httpx, json-repair, lancedb, networkx, nltk, numpy, openai, pandas, pyarrow, pydantic, …
```

fix: failed check graphrag version target when two "Version:" found
