mindverse/Second-Me

.gitignore, lpm_kernel/L2/data_pipeline/graphrag_indexing/.env, lpm_kernel/L2/data_pipeline/graphrag_indexing/settings.yaml
add graphrag indexing config files
=> add config file

lpm_kernel/api/domains/trainprocess/routes.py
delete lpm_kernel/api/domains/trainprocess/routes.py no use code
=> feat:delete no use code

CONTRIBUTING.md
CONTRIBUTING.md: Seond Me --> Second Me
=> CONTRIBUTING.md: Seond Me --> Second Me

.env, scripts/conda_utils.sh, scripts/setup.sh, scripts/start.sh
Support custom conda env config By setting CUSTOM_CONDA_MODE=true
=> feat: Add Custom Conda Env Config

README.md, environment.yml
#58 #61 
Add Description of Custom Conda Support
=> Feat: Add Description of Custom Conda Support In ReadMe

lpm_kernel/file_data/trainprocess_service.py
=> fix(train)

docker-compose.yml, lpm_kernel/L2/l2_generator.py, lpm_kernel/api/common/script_runner.py, lpm_kernel/api/domains/kernel2/routes_l2.py, lpm_kernel/file_data/trainprocess_service.py
=> Fix:Env detect & Fix Missing Merge Step

README.md
Better Version of Quick Start, as second-me support docker now.
=> Feat: BetterDescribeQuickStart

README_ja.md
I created Japanese translated README.
=> docs: add new README_ja.md

scripts/start_local.sh
=> Fix:Remove useless code

lpm_kernel/api/__init__.py, lpm_kernel/api/domains/trainprocess/routes.py, lpm_kernel/file_data/trainprocess_service.py
Is your feature request related to a problem? Please describe.
Optimize trainprocess
Describe the solution you'd like
Preserve all logs
Changed default retrain flag from 0
Reduced stop condition polling interval to 1 second for faster response.
Restructured code for better modularity, readability, and maintainability
=> fix: optimize trainprocess

.gitignore, Dockerfile.backend.apple, Makefile, README.md, docker-compose.yml, lpm_kernel/L2/train_for_user.sh, lpm_kernel/L2/utils.py
Tested locally on Apple M1, macOS: 14.5 (23F79)
=> Fix docker env on apple silicon

docs/Custom Model Config(Ollama).md
Add Custom Model Config Guidance
=> feat: add custom model config guidance

Makefile, README.md
Adjust env variable configuration for Apple Silicon platform
=> adjust env variable configuration for Apple Silicon

README.md
Add demonstration for docker desktop configuration
=> Tunning readme for docker desktop configuration

lpm_frontend/package-lock.json, lpm_frontend/package.json, lpm_frontend/yarn.lock
=> fix: update next & postcss

lpm_kernel/L2/utils.py, pyproject.toml
Add the functionality to download from ModelScope when downloading from Hugging Face fails.
=> feat: Implement model downloading from ModelScope.

CONTRIBUTING.md
new Branch management :) 
For Better Experience
=> feat: new branch management

CONTRIBUTING.md
Reverts mindverse/Second-Me#226
=> Revert "feat: new branch management"

lpm_kernel/api/domains/trainprocess/progress.py, lpm_kernel/file_data/trainprocess_service.py
This PR add step generate_biography
=> add step generate_biography

lpm_frontend/src/app/standalone/space/[spaceId]/page.tsx, lpm_frontend/src/components/API_MCP/MCPMode/content.tsx, lpm_frontend/src/components/Markdown/index.tsx, lpm_frontend/src/utils/markdown.tsx
Replaced legacy old markdown component
=> fix: fix markdown

lpm_kernel/L1/topics_generator.py
Topics generator timeout is too fast, modified to 30s.
=> Change topics_generator timeout to 30

lpm_kernel/api/domains/kernel/routes.py, lpm_kernel/train/trainprocess_service.py
=> fix:fix l1 save problem

mcp/mcp_public.py
Add MCP service for searching online Secondme models
@kevin-mindverse
=> mcp search online secondme model

lpm_frontend/src/app/home/components/Footer/index.tsx, lpm_frontend/src/layouts/DashboardLayout/Menu/index.tsx
Replaced two instructional links
=> feat: replace tutorial link

lpm_kernel/api/domains/kernel2/routes_l2.py, lpm_kernel/api/domains/loads/load_service.py
delete useless code in route_l2.py
=> delete useless code in route_l2.py

.env, lpm_kernel/L2/utils.py
Provide a selection of Chinese mirror websites for Huggingface.
@kevin-mindverse
=> Provide a selection of Chinese mirror websites for Huggingface

lpm_kernel/L2/train.py, lpm_kernel/api/domains/trainprocess/trainprocess_service.py
Fix progress bar display exception, progress bar data is obtained through call back.@kevin-mindverse
=> Fix progress bar display abnormality

lpm_kernel/L2/dpo/dpo_data.py, lpm_kernel/base/data.py, lpm_kernel/stage2/bio_qa.py, lpm_kernel/stage2/global_bio/base.py, lpm_kernel/stage2/shades/shades_generator.py, lpm_kernel/stage2/topics/topics_generator.py, lpm_kernel/stage2/wiki/base.py, lpm_kernel/stage3/generate_no_notes_questions.py, lpm_kernel/stage3/generate_notes_questions.py
=> remove additional data
